sudo: required
services:
    - docker
script:
    - docker build --tag yogeshkumar0/ci-cd .
    - docker run -d yogeshkumar0/ci-cd
    - docker images
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    - docker tag yogeshkumar0/ci-cd yogeshkumar0/ci-cd:0.0.1
    - docker push yogeshkumar0/ci-cd
after_script:
    - docker images
deploy:
    provider: heroku
    api_key:
        secure: sK6I+cTP9sUM+NJkBTLXgzmwhD/wAJV3VUd1HWjLAchrNeueZbCJJiO7WB0CgkOsXnMHFuABj0/eAsZ/R9CivPPkdKSvAnX1doV+rUkoYY4US5Vx6/z86e8EOo46obQbbi+W/x1MOmjywKya5MuxFPd0fFaSZbJ6E0GAdNy2/cXBcjI6suEygZkJ1hEUL4LKmAm6aqSN3yVS80i8oIsvEc/YRvFOd60/i7dzoLL6qtMmcC5HdG7FJxHWncdWAIFzTtYEtGIbwJv8noEkMVqRhJxncC/SpDUjDqIBkC3Ujp08K979UYkK3d/DD9qTTU/qQaXbTh6yy8tdJKDu2GTJL1vO84S5ltXUK3eL/ltukqTGFqIAGglPI7C4H1K9Ez7rOYWQqZZFKwLl5hiPE9x5Q7chDfnHMaoBkUmK1Beh0+v/9/tg4j1K9rv6ETJOfFgzZ5l1be0az5gVfa1dwf0AekY7doael+sm2Wiigvtt6SzZIERhd9PdUxPzKTqz9BQq5girDejKtS5kvGJyvgVBr5ReA7/5E+Bqt48H7jw96s9rfKjT+Vn00Ua0qyAhkAPr8AzKNfAg7sVS4ZzwrUqjq56PF30LsAoY/I2U9EUwbo/1mIw6VZmX2Nnc6Sv0VfAfjm1gR/RPb6xjSx0iZW5OphzF6gJY5RU7XPB9b/wYJrk=
    on:
        branch: master
