sudo: required
services:
    - docker
script:
    - docker build --tag snap-crackle-pop/ci-cd .
    - docker run -d snap-crackle-pop/ci-cd
after_script:
    - docker images
before_deploy:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
deploy:
    provider: heroku
    script: docker push snap-crackle-pop/ci-cd
    on:
        branch: master
